# Generated by Django 5.0 on 2023-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, db_column='P_Name', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('passterm', models.CharField(blank=True, db_column='PassTerm', max_length=20, null=True)),
            ],
            options={
                'db_table': 'loginfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=50, null=True)),
                ('date_ordered', models.DateTimeField(blank=True, db_column='Date_Ordered', null=True)),
                ('complete', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('p_name', models.CharField(blank=True, db_column='P_Name', max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
